import program.scene.eye.eye
import program.scene.sdf_bm.sdf_bm
import program.scene.template.template
import program.scene.abstractsqrt.abstractsqrt
import program.scene.truchet.truchet
import program.scene.lumtriangle.lumtriangle
import program.scene.gsstylized.gsstylized
import program.scene.patatrack3d.patatrack3d
import program.scene.cube.cube
import program.scene.rainbowroad.rr