import program.scene.eye.eye
import program.scene.sdf_bm.sdf_bm
import program.scene.template.template
import program.scene.abstractsqrt.abstractsqrt
import program.scene.truchet.truchet
import program.scene.lumtriangle.lumtriangle
import program.scene.gsstylized.gsstylized
import program.scene.patatrack3d.patatrack3d
import program.scene.cube.cube
import program.scene.rainbowroad.rr
import program.scene.psyspin.psyspin
import program.scene.hexshadows.hexshadows
import program.scene.neonparty.neonparty
import program.scene.pharmacy.pharmacy
import program.scene.pingouin.pingouin
import program.scene.dome.dome
import program.scene.hexagons.hexagons
import program.scene.texture.texture